---
- name: Bootstrap ansible-pull
  import_playbook: playbooks/bootstrap/play.yml

- name: Install Docker compose services
  import_playbook: playbooks/compose/play.yml

- name: Laptop setup
  import_playbook: playbooks/laptop/play.yml

- name: Fedora 42
  ansible.builtin.import_playbook: playbooks/fedora42/play.yml

- name: Proxmox
  ansible.builtin.import_playbook: playbooks/proxmox/play.yml
...
