---
- name: INIT
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Package managers
      ansible.builtin.package: name={{ pkg }} state=installed
      become: true
      vars:
        pkg: [cargo, cabal, python-pip, pipx]

    - name: PIP
      ansible.builtin.pip: name={{ pkg }} state=present
      vars:
        pkg: [polars, pandas]

    - name: PIPX
      community.general.pipx: name={{ pkg }} state=install
      environment:
        PIPX_HOME: "{{ ansible_user_dir }}/opt/pipx"
        PIPX_BIN_DIR: "{{ ansible_user_dir }}/opt/pipx/bin"
      vars:
        pkg: [black, isort, nose, poetry, pyflakes, pytest, ruff]

    - name: CARGO
      community.general.cargo: name={{ pkg }} state=present
      environment:
        CARGO_HOME: {{ ansible_user_dir }}/opt/pipx"
      vars:
        pkg: [rg, fd, sd, topgrade, vivid]

    - name: Emacs
      ansible.builtin.package: name={{ pkg }} state=installed
      become: true
      vars:
        pkg: [emacs]
...
