---
- name: COMPOSE
  hosts: 'virtual'
  connection: local
  gather_facts: false
  become: false
  become_user: root
  run_once: true
  no_log: false
  handlers:
    - name: TODO compose handlers
      meta: noop

  tasks:
    - name: Create 'compose.yml' to '/opt'
      ansible.builtin.copy:
        dest: /opt/compose.yml
        # src: docker/compose.yml
        mode: '0600'
        owner: 'root'
        group: 'root'
        content: >-
          {{ composefile | to_yaml }}

    - name: "Create '/opt/tailscale.env'"
      ansible.builtin.copy:
        dest: '/opt/tailscale.env'
        content: |
          TS_AUTHKEY={{ ts-admin-access-token | d(ts_key_default) }}
        mode: '0600'
        owner: 'root'
        group: 'root'

    - name: Copy files to remote locations
      loop: "{{ do_hosts|d([ansible_host]) }}"
      copy:
        mode: '0600'
        owner: 'root'
        group: 'root'
        content: |
          {{ _services | to_yaml }}
      vars:
        _services:
          whoami:
            image: "traefik/whoami"
            container_name: "whoami-{{ item }}"
            labels:
              - "traefik.enable=true"
              - "traefik.http.routers.whoami.rule=Host(`{{ item }}`)"
              - "traefik.http.routers.whoami.entrypoints=web"

    - name: "Start 'tailscale'"
      ansible.builtin.shell: >-
        docker compose up --detach
      args:
        chdir: '/opt'

  vars:
    ts-admin-access-token: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      61656631616131373632356465653032333830636238313538653266623836376539666361313931
      6136326632366339303630666436323363326435626334650a366465363435306139343039383061
      63333934333730356538333538356563393263643230353036333431383333393430613364643038
      6164346339663839660a386365663834353263353735353664623337616166373533653765303463
      37356633366635643736646532653565616133383933323538646530336462666438626237363835
      64666531323965313230346131386261613533353435363062303133366431343438633736336633
      393031346339623962363864653862633135

    composefile:
      services:
        traefik:
          image: "traefik:v3.5"
          container_name: "traefik"
          command:
            #- "--log.level=DEBUG"
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entryPoints.web.address=:80"
          ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
          volumes: &DOCKER_HOST
            - "/var/run/docker.sock:/var/run/docker.sock:ro"

        tailscale-nginx:
          image: "tailscale/tailscale:latest"
          hostname: "{{ ansible_host }}"
          environment:
            - "TS_STATE_DIR=/var/lib/tailscale"
            - "TS_USERSPACE=false"
            # - "TS_EXTRA_ARGS=--advertise-tags=tag:container --reset"
          devices:
            - "/dev/net/tun:/dev/net/tun"
          cap_add:
            - "net_admin"
          restart: "unless-stopped"
          env_file:
            - "tailscale.env"
          volumes:
            - "/opt/tailscale-nginx/state:/var/lib/tailscale"

        # nginx:
        #   image: "nginx"
        #   depends_on:
        #     - "tailscale-nginx"
        #   network_mode: "service:tailscale-nginx"

        autoheal:
          image: "willfarrell/autoheal"
          environment:
            AUTOHEAL_CONTAINER_LABEL: "all"
            AUTOHEAL_INTERVAL: 5
            AUTOHEAL_START_PERIOD: 0
            AUTOHEAL_DEFAULT_STOP_TIMEOUT: 10
            DOCKER_SOCK: "/var/run/docker.sock"
            CURL_TIMEOUT: 30
          privileged: true
          restart: "always"
          volumes: 
            - "/var/run/docker.sock:/var/run/docker.sock:rw"

- name: UFW
  hosts: 'ubuntu-vm'
  connection: local
  gather_facts: false
  become: false
  become_user: root
  no_log: false
  tasks:
    - name: Open HTTP and HTTPS
      loop:
        - 80
        - 443
      community.general.ufw:
        rule: allow
        port: '{{ item }}'
        proto: tcp
...
