---
- name: GALAXY
  hosts: 'root'
  user: 'root'
  tasks:
    - vars:
        data:
          roles:
            - name: 'Cargo'
              src: 'ssh://git@github.com/{{ pull_user }}/ansible-role-cargo.git'
              version: master
              scm: git
          collections:
            - name: 'community.general'
            - name: 'community.proxmox'
            - name: 'community.digitalocean'
            - name: 'community.docker'
      copy:
        dest: /opt/ansible/requirements.yml
        content: |
          {{ data | to_yaml }}

    - ansible.builtin.cron:
        state: "present"
        name: "ansible roles"
        weekday: "*"
        minute: "*"
        hour: "*"
        month: "*"
        user: "root"
        job: "ansible-galaxy install --role-file /opt/ansible/requirements.yml"
        cron_file: "ansible_galaxy"
