---
- name: GALAXY
  hosts: 'root'
  user: 'root'
  tasks:
    - file:
        dest: /opt/ansible
        state: directory

    - vars:
        data:
          roles:
            - name: geerlingguy.docker
            - name: geerlingguy.pip
            # - name: 'Cargo'
            #   src: 'https://github.com/{{ pull_user }}/ansible-role-cargo.git'
            #   version: master
            #   scm: git
          collections:
            - name: 'community.general'
            - name: 'community.proxmox'
            - name: 'community.digitalocean'
            - name: 'community.docker'
      copy:
        dest: /opt/ansible/requirements.yml
        content: |
          {{ data | to_yaml }}

    - ansible.builtin.shell: >-
        ansible-galaxy install --role-file /opt/ansible/requirements.yml

    - ansible.builtin.cron:
        state: "present"
        name: "Ansible roles & collections"
        weekday: "*"
        minute: "*"
        hour: "*"
        month: "*"
        user: "root"
        job: "ansible-galaxy install --role-file /opt/ansible/requirements.yml"
        cron_file: "ansible_galaxy"
