#!/bin/bash
source /etc/os-release

case $(hostname -s) in
  ( docker* )
  if ! command -v docker &>/dev/null; then
    curl -sL https://get.docker.com | bash
  fi

  if ! [ -d /opt/compose ]; then
    git -C /opt clone https://github.com/{{ pull_user }}/compose
  fi
  cat <<EOF | install -DTv /dev/stdin /opt/compose/compose.yml
# TODO
---
...
EOF
  ;;
esac
