#!/bin/bash
source /etc/os-release

case $(hostname -s) in
  ( docker* )
  if ! [ -s /var/cache/apt/pkgcache.bin ]; then
    apt update
  fi

  if ! command -v curl &>/dev/null; then
    apt install -y curl
  fi

  if ! command -v git &>/dev/null; then
    apt install -y git
  fi

  if ! command -v docker &>/dev/null; then
    command curl -sL https://get.docker.com | bash
  fi

  if ! [ -d /opt/compose ]; then
    command git -C /opt clone https://github.com/{{ pull_user }}/compose
  fi

  cat <<EOF | install --compare -DTv /dev/stdin /opt/compose/compose.yml
# TODO
---
include:
  - path:
      - traefik/compose.yml
...
EOF
  ;;
esac
