---
- name: PROXMOX
  hosts: 'proxmox'
  connection: local
  gather_facts: false
  become: false
  become_user: root
  run_once: true
  tasks:
    - when: terraform.role not in roles
      ansible.builtin.shell: >-
        pveum role add {{ terraform.role }} -privs '{{ terraform.privs }}'

    - when: terraform.user not in users
      ansible.builtin.shell: >-
        pveum user add {{ terraform.user }} --password '{{ terraform.password }}'

    - when: terraform.user not in users
      ansible.builtin.shell: |
        pveum aclmod / -user {{ terraform.user }} -role {{ terraform.role }} || true

    - loop:
        - debian-12-standard_12.7-1_amd64.tar.zst
        - ubuntu-24.04-standard_24.04-2_amd64.tar.zst
      ansible.builtin.get_url:
        url: >-
          http://download.proxmox.com/images/system/{{ item }}
        dest: >-
          {{ proxmox_lxc_image_dir }}/{{ item }}

    - loop:
        - 'debian-12-turnkey-ansible_18.0-1_amd64.tar.gz'
      ansible.builtin.get_url:
        url: >-
          http://mirror.turnkeylinux.org/turnkeylinux/images/proxmox/{{ item }}
        dest: >-
          {{ proxmox_lxc_image_dir }}/{{ item }}

    - ansible.builtin.file:
        dest: '/var/lib/vz/snippets'
        state: 'directory'

    - ansible.builtin.uri:
        method: GET
        url: >-
          https://download.docker.com/linux/ubuntu/gpg
        return_content: true
      register: api_response

    - ansible.builtin.copy:
        dest: '/var/lib/vz/snippets/ubuntu-docker.yml'
        content: |
          #cloud-config
          {{ data | to_yaml }}

      vars:
        data:
          package_upgrade: false
          package_update: true
          packages:
            - docker-ce
            - docker-ce-cli
          apt:
            # deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu   jammy stable
            docker.list:
              source: >-
                deb [arch=amd64] https://download.docker.com/linux/ubuntu   jammy stable
              key: >-
                {{ api_response.content }}

  vars:
    proxmox_lxc_image_dir: >-
      /var/lib/vz/template/cache

    roles: >-
      {{ proxmox_roles | map(attribute='roleid') }}

    users: >-
      {{ proxmox_users | map(attribute='userid') }}

    terraform:
      user: "terraform-prov@pve"
      role: "TerraformProv"
      privs: >-
        Datastore.AllocateSpace Datastore.AllocateTemplate Datastore.Audit
        Pool.Allocate Sys.Audit Sys.Console Sys.Modify VM.Allocate VM.Audit
        VM.Clone VM.Config.CDROM VM.Config.Cloudinit VM.Config.CPU
        VM.Config.Disk VM.Config.HWType VM.Config.Memory VM.Config.Network
        VM.Config.Options VM.Migrate VM.Monitor VM.PowerMgmt SDN.Use
      password: !vault |
                $ANSIBLE_VAULT;1.1;AES256
                30613237653361313365313238353137333839373466656334623665643334643565303965333832
                3431336230386264353263303538366435346438646338640a383538323934303834326238636666
                34636434646631653437313661383539363564633037346436346235636464353266633166313663
                3735653232616166330a633133356538306631613335356236303133346663386136313861333730
                33643161373464653639326462666162376664623563663037313962323932666432
...
