---
- name: COMPOSE
  hosts: virtual
  connection: local
  gather_facts: false
  become: false
  become_user: root
  no_log: false
  tasks:
    - name: Copy 'compose.yml' to '/opt'
      ansible.builtin.copy:
        dest: /opt/compose.yml
        source: docker/compose.yml
        mode: '0600'
        owner: 'root'
        group: 'root'

    - name: Execute shell commands on targets
      ansible.builtin.shell: >-
        docker compose up --detach tailscale

...
