---
- name: COMPOSE
  hosts: virtual
  connection: local
  gather_facts: false
  become: false
  become_user: root
  no_log: false
  tasks:
    - name: Copy 'compose.yml' to '/opt'
      ansible.builtin.copy:
        dest: /opt/compose.yml
        src: docker/compose.yml
        mode: '0600'
        owner: 'root'
        group: 'root'

    - name: Start 'tailscale'
      ansible.builtin.shell:
        cmd: >-
            docker compose up --detach tailscale
      args:
        chdir: /opt

...
